# Generated by Django 4.2.4 on 2023-08-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Upper-Intermediate'), ('4', 'Advance'), ('5', 'Mastery')], max_length=1)),
                ('participants', models.ManyToManyField(blank=True, related_name='p_courses', to='persons.participant')),
                ('presenters', models.ManyToManyField(blank=True, related_name='p_courses', to='persons.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TakeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_take_courses', to='persons.participant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_take_courses', to='toturials.course')),
            ],
        ),
    ]
