# Generated by Django 4.2.4 on 2023-08-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toturials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takecourse',
            old_name='Participant',
            new_name='participant',
        ),
    ]
