# Generated by Django 4.2.4 on 2023-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.PositiveIntegerField(),
        ),
    ]
