# Generated by Django 4.2.4 on 2023-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_is_complete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
